### ISSUE TITLE
Crash on reload of save

### ISSUE THREAD

**Issue by FDinolfo** [MathIsFun0/Cryptid#120]
I was having a fun time on the Antimatter deck, just goofing off. I was getting some stupid scores, and money had gone to naneinf. I went to main menu and closed the game to get a bite to eat. When I came back and started up again, and loaded the save, I got an immediate crash just after the Jimball theme started playing.

Here's the trace.

Oops! The game crashed:
functions/state_events.lua:2195: attempt to compare number with nil

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0~ALPHA-0813a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Version: 0.4.3i, Uses Lovely]
    2: Talisman by MathIsFun_, Mathguy24, jenwalter666 [ID: Talisman, Version: 2.0.0-beta4, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua upvalue 'gfer' at file 'functions/state_events.lua:2195'
Local variables:
 pitch = number: 1.37
 dollars = number: 355.8
 (*temporary) = nil
 (*temporary) = number: 5
 (*temporary) = number: 1
 (*temporary) = number: 4
 (*temporary) = nil
 (*temporary) = table: 0x2bff9488  {tally:67, triggered:false, tag_sprite:table: 0x2bfff228, pos:table: 0x2ad1b390 (more...)}
 (*temporary) = table: 0x2b1dccb0  {type:eval}
 (*temporary) = nil
 (*temporary) = boolean: false
 (*temporary) = string: "attempt to compare number with nil"
(4) Lua field 'evaluate_round' at file 'main.lua:1789'
Local variables:
 arer = Lua function '?' (defined at line 1046 of chunk functions/common_events.lua)
(5) Lua field 'func' at file 'game.lua:3565'
(6) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x2b918178  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x2b77d110 (more...)}
 _results = table: 0x2a9fd378  {blocking:true, pause_skip:false, time_done:false, completed:false}
(7) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x2ac76898  {queue_last_processed:30.433333333333, queues:table: 0x2ac06990, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00936715
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x2ac06990  {unlock:table: 0x2ac22378, other:table: 0x2a735470, tutorial:table: 0x2a93c740 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x2ac2c998  {1:table: 0x2ac838b8, 2:table: 0x2b918178, 3:table: 0x2ba53f20, 4:table: 0x2ae004a8 (more...)}
 blocked = boolean: false
 i = number: 2
 results = table: 0x2a9fd378  {blocking:true, pause_skip:false, time_done:false, completed:false}
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2664'
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
 http_resp = nil
(9) Lua upvalue 'upd' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
(10) Lua upvalue 'upd' at file 'main.lua:1685'
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
(11) Lua upvalue 'upd' at file 'Items/Blinds.lua:1103' (from mod with id Cryptid)
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
(12) Lua upvalue 'upd' at file 'Items/CodeCards.lua:2504' (from mod with id Cryptid)
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
(13) Lua upvalue 'upd' at file 'Items/MiscJokers.lua:4488' (from mod with id Cryptid)
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
(14) Lua method 'update' at file 'Cryptid.lua:1141' (from mod with id Cryptid)
Local variables:
 self = table: 0x2a72f000  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x2bfcf418 (more...)}
 dt = number: 0.00936715
(15) Lua field 'update' at file 'main.lua:936'
Local variables:
 dt = number: 0.00936715
(16) Lua function '?' at file 'main.lua:880' (best guess)
(17) global C function 'xpcall'
(18) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 851 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

I also included a copy of the save itself.
[3.zip](https://github.com/user-attachments/files/16646932/3.zip)

**Comment by Jevonnissocoolman** [comment]
I think this was fixed in a newer version in the source code

**Comment by FDinolfo** [comment]
I was using the source from a couple of days ago. So it seems like it's
still a thing.

**Comment by MathIsFun0** [comment]
I think this is something that happens when a value reaches naneinf in general. Going to leave it open because I will probably get to fixing it at some point

**Comment by FDinolfo** [comment]
Cool. Works for me. In the meantime, I know not to save and reload if
anything went to Naneinf.

**Comment by MathIsFun0** [comment]
closing this because there are more guardrails now to prevent values reaching infinity
