### ISSUE TITLE
Game crashes on scoring 5 of a kind:

### ISSUE THREAD

**Issue by mmmotion** [MathIsFun0/Cryptid#133]
Oops! The game crashed:
[SMODS Cryptid "Items/xEpicJokers.lua"]:156: attempt to index local 'tot' (a number value)

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0~ALPHA-0820c-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Version: 0.5.0-pre, Uses Lovely]
    2: Talisman by MathIsFun_, Mathguy24, jenwalter666 [ID: Talisman, Version: 2.0.0-beta5, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'calculate' at file 'Items/xEpicJokers.lua:156' (from mod with id Cryptid)
Local variables:
 self = table: 0x25f04870  {alerted:false, object_type:Joker, _saved_d_u:true, original_key:sync_catalyst (more...)}
 card = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
 tot = number: 9868
 (*temporary) = number: 9288
 (*temporary) = boolean: false
 (*temporary) = 1.00  {array:table: 0x25940b38, sign:1}
 (*temporary) = number: 1
 (*temporary) = string: "attempt to index local 'tot' (a number value)"
(4) Lua upvalue 'ccj' at file 'card.lua:2751'
Local variables:
 self = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
 obj = table: 0x25f04870  {alerted:false, object_type:Joker, _saved_d_u:true, original_key:sync_catalyst (more...)}
(5) Lua upvalue 'cj' at file 'main.lua:1705'
Local variables:
 self = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
(6) Lua upvalue 'scopecalculate' at file 'Cryptid.lua:316' (from mod with id Cryptid)
Local variables:
 self = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
 ggpn = number: 1
(7) Lua method 'calculate_joker' at file 'Items/Vouchers.lua:572' (from mod with id Cryptid)
Local variables:
 self = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
(8) Lua upvalue 'ec' at file 'functions/common_events.lua:740'
Local variables:
 card = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
 enhancement_calculated = boolean: false
 center = table: 0x25f04870  {alerted:false, object_type:Joker, _saved_d_u:true, original_key:sync_catalyst (more...)}
 ret = table: 0x25a63c90  {}
 seals = nil
 jokers = nil
(9) Lua global 'eval_card' at file 'Cryptid.lua:292' (from mod with id Cryptid)
Local variables:
 card = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 context = table: 0x25a63c68  {poker_hands:table: 0x25dac5a8, scoring_name:Flush Five, scoring_hand:table: 0x25a6c618 (more...)}
 ggpn = number: 1
(10) Lua upvalue 'gfep' at file 'functions/state_events.lua:1632'
Local variables:
 e = nil
 text = string: "Flush Five"
 disp_text = string: "Flush Five"
 poker_hands = table: 0x25dac5a8  {Flush House:table: 0x25abb5c0, Full House:table: 0x25abb620, top:table: 0x257f3230 (more...)}
 scoring_hand = table: 0x25a6c618  {1:table: 0x260d7758, 2:table: 0x2606a900, 3:table: 0x25d8ada8, 4:table: 0x2606bab8 (more...)}
 non_loc_disp_text = string: "Flush Five"
 text_repl = string: "Flush Five"
 disp_text_repl = string: "Flush Five"
 non_loc_disp_text_repl = string: "Flush Five"
 pures = table: 0x25ac6c08  {}
 percent = number: 1.1
 percent_delta = number: 0.08
 hand_text_set = boolean: false
 modded = boolean: false
 mod_percent = boolean: false
 (for index) = number: 4
 (for limit) = number: 7
 (for step) = number: 1
 i = number: 4
 _card = table: 0x256566d8  {click_offset:table: 0x25c8ca90, children:table: 0x25d074e8, ambient_tilt:0.2 (more...)}
 edition_effects = table: 0x25a63c18  {}
(11) Lua upvalue 'gfep' at file 'main.lua:1719'
Local variables:
 e = nil
(12) Lua field 'evaluate_play' at file 'Items/Blinds.lua:1143' (from mod with id Cryptid)
Local variables:
 e = nil
(13) Lua field 'func' at file 'functions/state_events.lua:817'
(14) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x25ae6c58  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x25f895f0 (more...)}
 _results = table: 0x25c600f8  {blocking:true, pause_skip:false, time_done:false, completed:false}
(15) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x25994d58  {queue_last_processed:10.033333333333, queues:table: 0x256ebed0, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00834539
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x256ebed0  {unlock:table: 0x2599cf08, other:table: 0x25a06c20, tutorial:table: 0x255fe8c8 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x2599b8b0  {1:table: 0x259afb60, 2:table: 0x25ae6c58, 3:table: 0x25fab7e8, 4:table: 0x2570c340 (more...)}
 blocked = boolean: false
 i = number: 2
 results = table: 0x25c600f8  {blocking:true, pause_skip:false, time_done:false, completed:false}
(16) Lua upvalue 'gameUpdateRef' at file 'game.lua:2664'
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
 http_resp = nil
(17) Lua upvalue 'upd' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
(18) Lua upvalue 'upd' at file 'main.lua:1685'
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
(19) Lua upvalue 'upd' at file 'Items/Blinds.lua:1103' (from mod with id Cryptid)
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
(20) Lua upvalue 'upd' at file 'Items/CodeCards.lua:2880' (from mod with id Cryptid)
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
(21) Lua upvalue 'upd' at file 'Items/MiscJokers.lua:4577' (from mod with id Cryptid)
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
(22) Lua method 'update' at file 'Cryptid.lua:1152' (from mod with id Cryptid)
Local variables:
 self = table: 0x2544c2d8  {ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x25abfba8 (more...)}
 dt = number: 0.00834539
(23) Lua field 'update' at file 'main.lua:936'
Local variables:
 dt = number: 0.00834539
(24) Lua function '?' at file 'main.lua:880' (best guess)
(25) global C function 'xpcall'
(26) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 851 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by mmmotion** [comment]
![image](https://github.com/user-attachments/assets/28d1f983-346e-46e5-ac6b-a6436f81b06d)

If I play 5 or 4 lucky queens with RIGGED tag, it breaks :(
It finally worked with only 3 of them...

**Comment by MathIsFun0** [comment]
It's an issue with my bugfix for Sync Catalyst. Will get to patching it today

**Comment by mmmotion** [comment]
Do you have any tips on how to avoid this until it's fixed? 
I got Sync Catalyst again, along with a pretty sweet setup - I'd like to ride this pony till the end :)

![image](https://github.com/user-attachments/assets/3aa0bd35-0072-42a4-a2a6-dbe1c38ce252)

**Comment by MathIsFun0** [comment]
Try using OmegaNum if you aren't

**Comment by mmmotion** [comment]
Not sure how I would "use" OmegaNum, what I can say is that now I'm getting much bigger numbers than in the reported run (initial issue), so it's not just an issue with the max round score...

![image](https://github.com/user-attachments/assets/e1ea0eec-948c-4cbe-a284-2861253ad19a)

**Comment by mmmotion** [comment]
![image](https://github.com/user-attachments/assets/ab5d2a5a-074d-4f71-be78-0ab3b2e89add)

**Comment by MathIsFun0** [comment]
Going to close this as I believe the issue was fixed
