### ISSUE TITLE
Using Multiply CODE card on the ONE FOR ALL joker has no effect

### ISSUE THREAD

**Issue by mmmotion** [MathIsFun0/Cryptid#135]
![image](https://github.com/user-attachments/assets/4ccfa96b-ac8d-4c14-9a3f-7436c402b262)

The numbers on the card change, but this doesn't translate into increase of 5 target values...

**Comment by Jevonnissocoolman** [comment]
yeah it's coded to only give stats when added or removed so updating it's stats with multiply won't do anything, not much can really be done about it

**Comment by MathIsFun0** [comment]
I think there is a way to fix this though, might try my hand at it today

**Comment by MathIsFun0** [comment]
also the name should change to two for all when that happens /j

**Comment by mmmotion** [comment]
Hahaha, nah - you modify the downstream properties of the card, not it's actual identity :)

In all seriousness, you've created a real monster here - I'm having so much fun with this mod!
The only issue I have now is that the counting takes sooooo long when you break the game with jokers. 
Maybe it wouldn't be a bad idea to include more game speed options, if this is possible?

**Comment by MathIsFun0** [comment]
There is a setting in Talisman to remove scoring animations completely.

**Comment by Jevonnissocoolman** [comment]
hey, it's been a while
this should now be fixed in the newest source code version
