### ISSUE TITLE
The green seal dosen't trigger

### ISSUE THREAD

**Issue by wolfONdrugs** [MathIsFun0/Cryptid#182]
The green seal doesn't seem to be working
It doesn't trigger when played or unscoring like stated.

my mod list

![Screenshot 2024-09-12 155605](https://github.com/user-attachments/assets/5e727077-103f-4c18-a2ac-a297b335de53)

**Comment by Jevonnissocoolman** [comment]
it works fine for me, are you sure you are understanding the effect correctly?
For it to trigger it needs to be played, but not scored
For example playing a three of a kind with an unscored green seal card with it would trigger the green seal card

**Comment by MathIsFun0** [comment]
Going to close this as there is not any evidence shown. If you could send a video of the effect failing or your current mods folder as a zip, that would be helpful in debugging this.
