### ISSUE TITLE
I got Infinity score but lost the blind

### ISSUE THREAD

**Issue by NyaightHazard** [MathIsFun0/Cryptid#184]
![result image](https://github.com/user-attachments/assets/982f682f-32cc-493b-8d57-07e90ced09ba)

## Whats happend
1. I had these Jokers:
> Compound Interest [Rare] (about e100%)
> Scalae [Exotic] (about degree-130)
> Dobule Scale [Epic]
> Sync Catalyst [Epic]
> etc ...

2. Got naneinf payout and my money became $naneinf

3. I bought Bull [vanilla common, +2 chips for each $1] Joker
   It said (Currently +naneinf Chips)

4. While blind each hand got Infinity x Infinity = Infinity score but couldn't beat blind.

##  Suggestions
1. limit the Compound Interest up to $e299
2. [Talisman] Fix like Infinity score can beat any blind
3. [Talisman] Applies scale break to money too

**Comment by Jevonnissocoolman** [comment]
Yeah getting infinity on omeganum talisman will never win against a blind
This is something that has been present since this was a thing and it isn't something that is planned to be fixed
