### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by mushybeep** [MathIsFun0/Cryptid#186]
Oops! The game crashed:
Syntax error: functions/state_events.lua:118: '}' expected (to close '{' at line 108) near 'if'

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: ???
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta7

Stack Traceback
===============
(3)  C function 'function: 0x38a6bc40'
(4) global C function 'require'
(5) main chunk of file 'main.lua' at line 825
(6) global C function 'require'
(7) Love2D function at file 'boot.lua:323' (best guess)
Local variables:
 c = table: 0x38a6e1a0  {identity:false, version:11.5, accelerometerjoystick:true, modules:table: 0x38a6e1c8 (more...)}
 openedconsole = boolean: false
 confok = boolean: true
 conferr = nil
(8) global C function 'xpcall'
(9) Love2D function at file 'boot.lua:362' (best guess)
Local variables:
 result = boolean: true
(10) global C function 'xpcall'
(11) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by aknicholas** [comment]
I'm also getting this after a fresh install

**Comment by Jevonnissocoolman** [comment]
This is Happening because of a lovely file in Jen's almanac alongside Lovely Beta 7
To fix this, you either need to 
1: Downgrade your lovely and go back to beta7
OR 2: manually edit the priority of Jen's almanac's Lovely.toml to a lower number (say 10,000)
This should fix the issue that is happening to both of you
