### ISSUE TITLE
My game crashes when playing a high card that would win otherwise

### ISSUE THREAD

**Issue by Joe-mama131** [MathIsFun0/Cryptid#187]
I have way too many jokers to even count but here's the crash report

`Oops! The game crashed:
[SMODS Cryptid "Cryptid.lua"]:557: attempt to index a number value

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: 1.0.0~ALPHA-0906b-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Choose First Shop Joker by infarctus [ID: choose_first_shop_Joker]
    2: JokerSellValue by OppositeWolf770 [ID: JokerSellValue, Priority: 100000, Version: 1.2.1]
    3: Talisman by MathIsFun_, Mathguy24, jenwalter666 [ID: Talisman, Version: 2.0.0-beta7, Uses Lovely]
    4: Incantation by jenwalter666, MathIsFun_ [ID: incantation, Priority: 9e+301, Version: 0.5.3, Uses Lovely]
    5: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Priority: 1e+299, Version: 0.5.0, Uses Lovely]
    6: Nopeus by jenwalter666, stupxd [ID: nopeus, Version: 2.1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua method 'cry_double_scale_calc' at file 'Cryptid.lua:557' (from mod with id Cryptid)
Local variables:
 self = table: 0x3d598188  {click_offset:table: 0x3d5982e8, children:table: 0x3d598d28, ambient_tilt:0.2 (more...)}
 orig_ability = table: 0x3d5f8e40  {bonus:0, h_mult:0, extra:0.1, x_chips:0, hands_played_at_create:38, mult:0 (more...)}
 in_context_scaling = boolean: false
 orig_scale_base = number: 68
 orig_scale_scale = nil
 jkr = table: 0x3d598188  {click_offset:table: 0x3d5982e8, children:table: 0x3d598d28, ambient_tilt:0.2 (more...)}
 dbl_info = table: 0x3ba2bc08  {offset:1, base:table: 0x3ba2bcf8, scaler_base:50, scaler:table: 0x3ba2bd58 (more...)}
 (*temporary) = number: 0.1
 (*temporary) = string: "mult"
 (*temporary) = string: "eternal"
 (*temporary) = table: 0x3a9fee90  {loc_vars:function: 0x3a7c1468, _saved_d_u:true, original_key:eternal, sticker_sprite:table: 0x3a56e130 (more...)}
 (*temporary) = nil
 (*temporary) = string: "eternal"
 (*temporary) = 0.00  {array:table: 0x3d5f8880, sign:1}
 (*temporary) = number: 1
 (*temporary) = number: 0
 (*temporary) = 0.00  {array:table: 0x3d5f8880, sign:1}
 (*temporary) = boolean: false
 (*temporary) = boolean: false
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = table: 0x3d5be8f0  {bonus:0, h_mult:0, extra:table: 0x3d5be918, d_size:0, x_chips:0, hands_played_at_create:32 (more...)}
 (*temporary) = boolean: false
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = number: 874
 (*temporary) = table: 0x3bc3f408  {bonus:0, h_mult:0, extra:table: 0x3bc3f738, h_size:0, x_chips:0, hands_played_at_create:32 (more...)}
 (*temporary) = number: nan
 (*temporary) = string: "d_size"
 (*temporary) = number: 0
 (*temporary) = string: "number"
 (*temporary) = number: 0
 (*temporary) = boolean: false
 (*temporary) = string: " compatible "
 (*temporary) = string: "attempt to index a number value"
(4) Lua upvalue 'cj' at file 'Cryptid.lua:685' (from mod with id Cryptid)
Local variables:
 self = table: 0x3d598188  {click_offset:table: 0x3d5982e8, children:table: 0x3d598d28, ambient_tilt:0.2 (more...)}
 context = table: 0x3d5f8de0  {retrigger_joker_check:true, other_card:table: 0x3b6410b8}
 ggpn = number: 1e+300
 orig_ability = table: 0x3d5f8e40  {bonus:0, h_mult:0, extra:0.1, x_chips:0, hands_played_at_create:38, mult:0 (more...)}
 in_context_scaling = boolean: false
 ret = nil
 trig = nil
(5) Lua method 'calculate_joker' at file 'Items/CodeCards.lua:3083' (from mod with id Cryptid)
Local variables:
 self = table: 0x3d598188  {click_offset:table: 0x3d5982e8, children:table: 0x3d598d28, ambient_tilt:0.2 (more...)}
 context = table: 0x3d5f8de0  {retrigger_joker_check:true, other_card:table: 0x3b6410b8}
(6) Lua upvalue 'ccj' at Steamodded file 'core/overrides.lua:2076' 
Local variables:
 self = table: 0x3b6410b8  {click_offset:table: 0x3b641450, children:table: 0x3b648010, ambient_tilt:0.2 (more...)}
 context = table: 0x3d57da60  {callback:function: 0x3d57db50, before:true, scoring_name:High Card, scoring_hand:table: 0x3beab848 (more...)}
 ret = table: 0x3d5a1dc8  {joker_repetitions:table: 0x3d5a1e60}
 triggered = boolean: true
 _ret = nil
 (for index) = number: 198
 (for limit) = number: 198
 (for step) = number: 1
 i = number: 198
(7) Lua upvalue 'cj' at file 'main.lua:1681'
Local variables:
 self = table: 0x3b6410b8  {click_offset:table: 0x3b641450, children:table: 0x3b648010, ambient_tilt:0.2 (more...)}
 context = table: 0x3d57da60  {callback:function: 0x3d57db50, before:true, scoring_name:High Card, scoring_hand:table: 0x3beab848 (more...)}
(8) Lua upvalue 'cj' at file 'Cryptid.lua:676' (from mod with id Cryptid)
Local variables:
 self = table: 0x3b6410b8  {click_offset:table: 0x3b641450, children:table: 0x3b648010, ambient_tilt:0.2 (more...)}
 context = table: 0x3d57da60  {callback:function: 0x3d57db50, before:true, scoring_name:High Card, scoring_hand:table: 0x3beab848 (more...)}
 ggpn = number: 1e+09
 orig_ability = table: 0x3d57dbc8  {bonus:0, h_mult:0, extra:table: 0x3d57dc28, x_chips:0, hands_played_at_create:18 (more...)}
 in_context_scaling = boolean: false
(9) Lua method 'calculate_joker' at file 'Items/CodeCards.lua:3083' (from mod with id Cryptid)
Local variables:
 self = table: 0x3b6410b8  {click_offset:table: 0x3b641450, children:table: 0x3b648010, ambient_tilt:0.2 (more...)}
 context = table: 0x3d57da60  {callback:function: 0x3d57db50, before:true, scoring_name:High Card, scoring_hand:table: 0x3beab848 (more...)}
(10) Lua upvalue 'ec' at file 'functions/common_events.lua:737'
Local variables:
 card = table: 0x3b6410b8  {click_offset:table: 0x3b641450, children:table: 0x3b648010, ambient_tilt:0.2 (more...)}
 context = table: 0x3d57da60  {callback:function: 0x3d57db50, before:true, scoring_name:High Card, scoring_hand:table: 0x3beab848 (more...)}
 enhancement_calculated = boolean: false
 center = table: 0x3acd3388  {alerted:true, loc_vars:function: 0x3af1dbe8, object_type:Joker, _saved_d_u:true (more...)}
 ret = table: 0x3d57db78  {}
 seals = nil
 jokers = nil
(11) Lua global 'eval_card' at file 'Cryptid.lua:325' (from mod with id Cryptid)
Local variables:
 card = table: 0x3b6410b8  {click_offset:table: 0x3b641450, children:table: 0x3b648010, ambient_tilt:0.2 (more...)}
 context = table: 0x3d57da60  {callback:function: 0x3d57db50, before:true, scoring_name:High Card, scoring_hand:table: 0x3beab848 (more...)}
 ggpn = nil
(12) Lua upvalue 'gfep' at file 'functions/state_events.lua:848'
Local variables:
 e = nil
 text = string: "High Card"
 disp_text = string: "High Card"
 poker_hands = table: 0x3beab7b8  {Flush House:table: 0x3bead4e0, Full House:table: 0x3bead508, top:table: 0x3bead648 (more...)}
 scoring_hand = table: 0x3beab848  {1:table: 0x3c112250}
 non_loc_disp_text = string: "High Card"
 text_repl = string: "High Card"
 disp_text_repl = string: "High Card"
 non_loc_disp_text_repl = string: "High Card"
 pures = table: 0x3bead698  {}
 percent = number: 0.78
 percent_delta = number: 0.08
 hand_text_set = boolean: false
 (for index) = number: 190
 (for limit) = number: 197
 (for step) = number: 1
 i = number: 190
(13) Lua upvalue 'gfep' at file 'main.lua:1695'
Local variables:
 e = nil
(14) Lua field 'evaluate_play' at file 'Items/Blinds.lua:1143' (from mod with id Cryptid)
Local variables:
 e = nil
(15) Lua field 'func' at file 'functions/state_events.lua:723'
(16) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x3c26a7d8  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, created_on_pause:false (more...)}
 _results = table: 0x3a994f58  {blocking:true, pause_skip:false, time_done:false, completed:false}
(17) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x3aad8da8  {queue_last_processed:120.58333333333, queues:table: 0x3a836d48, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.0166091
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x3a836d48  {unlock:table: 0x3a836d70, other:table: 0x3a833790, tutorial:table: 0x3a568c80 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x3a568c58  {1:table: 0x3aaa74d0, 2:table: 0x3c26a7d8, 3:table: 0x3c26ac68, 4:table: 0x3c26ad10 (more...)}
 blocked = boolean: false
 i = number: 2
 results = table: 0x3a994f58  {blocking:true, pause_skip:false, time_done:false, completed:false}
(18) Lua upvalue 'gameUpdateRef' at file 'game.lua:2673'
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
 http_resp = nil
(19) Lua upvalue 'upd' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
(20) Lua upvalue 'upd' at file 'main.lua:1661'
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
(21) Lua upvalue 'upd' at file 'Items/Blinds.lua:1103' (from mod with id Cryptid)
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
(22) Lua upvalue 'upd' at file 'Items/CodeCards.lua:3058' (from mod with id Cryptid)
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
(23) Lua upvalue 'upd' at file 'Items/MiscJokers.lua:4913' (from mod with id Cryptid)
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
(24) Lua method 'update' at file 'Cryptid.lua:1706' (from mod with id Cryptid)
Local variables:
 self = table: 0x3a55e558  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3c1b6638 (more...)}
 dt = number: 0.0166091
(25) Lua field 'update' at file 'main.lua:936'
Local variables:
 dt = number: 0.0166091
(26) Lua function '?' at file 'main.lua:880' (best guess)
(27) global C function 'xpcall'
(28) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 851 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
`

**Comment by Jevonnissocoolman** [comment]
Update your mods, this is fixed in newer versions of Steamodded, Cryptid, Talisman etc...

**Comment by Joe-mama131** [comment]
is that 5.0.0? because i have that and it still occurs

**Comment by Jevonnissocoolman** [comment]
no, it's a newer version that's on the source code

**Comment by Joe-mama131** [comment]
Sorry but how do i get talisman? the most recent version isnt working

**Comment by Jevonnissocoolman** [comment]
you need to use the source code for that too
