### ISSUE TITLE
Crash when playing hand with Boredom

### ISSUE THREAD

**Issue by mpcomplete** [MathIsFun0/Cryptid#191]
I played KKKJJ. First King had a red seal. Game crashed. I reloaded, sold Boredom, tried again - no crash this time.

Jokers: abstract, brainstorm, midas mask, eternal photograph, reserved parking, ramen, BOREDOM

Oops! The game crashed:
functions/state_events.lua:901: 'for' limit must be a number

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: 1.0.0~ALPHA-0906b-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Aurinko by jenwalter666 [ID: aurinko, Priority: 9.9e+301, Version: 0.4.6]
    2: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Priority: 1e+299, Version: 0.5.0, Uses Lovely]
    3: Loop by jenwalter666 [ID: loop, Priority: -9999999999, Version: 0.1.1]
    4: Talisman by MathIsFun_, Mathguy24, jenwalter666 [ID: Talisman, Version: 2.0.0-beta7, Uses Lovely]
    5: Better Mouse And Gamepad by Kooluve [ID: BetterMouseAndGamepad]
    6: spacereroll by sishui [ID: spacereroll]
    7: Incantation by jenwalter666, MathIsFun_ [ID: incantation, Priority: 9e+301, Version: 0.5.2, Uses Lovely]
    8: Jen's Library by jenwalter666 [ID: JenLib, Version: 0.0.1]
    9: Nopeus by jenwalter666, stupxd [ID: nopeus, Version: 2.1.0, Uses Lovely]
Lovely Mods:
    1: Saturn
    2: Brainstorm

Stack Traceback
===============
(3) Lua field 'callback' at file 'functions/state_events.lua:901'
Local variables:
 card = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 ret = table: 0x3b196030  {joker_repetitions:table: 0x3af21508}
 (for index) = number: 1
 (for limit) = nil
 (for step) = number: 1
 (*temporary) = table: 0x3b196030  {joker_repetitions:table: 0x3af21508}
 (*temporary) = nil
 (*temporary) = table: 0x390fe600  {PATH:C:/Users/mpcom/AppData/Roaming/Balatro/Mods/Saturn, loadConfig:function: 0x39100898 (more...)}
 (*temporary) = boolean: false
 (*temporary) = string: "'for' limit must be a number"
(4) Lua upvalue 'ccj' at Steamodded file 'core/overrides.lua:2120' 
Local variables:
 self = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
 ret = table: 0x3b196030  {joker_repetitions:table: 0x3af21508}
 triggered = boolean: true
 _ret = nil
(5) Lua upvalue 'cj' at file 'main.lua:1813'
Local variables:
 self = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
(6) Lua upvalue 'cj' at file 'Cryptid.lua:676' (from mod with id Cryptid)
Local variables:
 self = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
 ggpn = number: 1
 orig_ability = table: 0x3a11f450  {bonus:0, h_mult:0, extra:table: 0x3a11f4b0, x_chips:0, hands_played_at_create:11 (more...)}
 in_context_scaling = boolean: false
(7) Lua upvalue 'cardCalculateJokerRef' at file 'Items/CodeCards.lua:3083' (from mod with id Cryptid)
Local variables:
 self = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
(8) Lua method 'calculate_joker' at line 112 of chunk '"7923"]'
Local variables:
 self = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
(9) Lua upvalue 'ec' at file 'functions/common_events.lua:682'
Local variables:
 card = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
 enhancement_calculated = boolean: false
 center = table: 0x396d0548  {alerted:true, loc_vars:function: 0x396d08c8, object_type:Joker, _saved_d_u:true (more...)}
 ret = table: 0x3a187440  {}
 chips = number: 0
 mult = number: 0
 x_mult = number: 0
 x_chips = number: 0
 e_chips = number: 0
 ee_chips = number: 0
 eee_chips = number: 0
 hyper_chips = table: 0x3a187468  {1:0, 2:0}
 e_mult = number: 0
 ee_mult = number: 0
 eee_mult = number: 0
 hyper_mult = table: 0x3a11f3e8  {1:0, 2:0}
 p_dollars = number: 0
(10) Lua global 'eval_card' at file 'Cryptid.lua:325' (from mod with id Cryptid)
Local variables:
 card = table: 0x3a79c190  {click_offset:table: 0x3b8327b8, static_rotation:false, ambient_tilt:0.2 (more...)}
 context = table: 0x3a187418  {callback:function: 0x3a4da318, other_card:table: 0x39fc4d08, poker_hands:table: 0x38d6c098 (more...)}
 ggpn = number: 1
(11) Lua upvalue 'gfep' at file 'functions/state_events.lua:899'
Local variables:
 e = nil
 text = string: "Full House"
 disp_text = string: "Full House"
 poker_hands = table: 0x38d6c098  {Flush House:table: 0x39b2e7e0, Full House:table: 0x3a705678, top:table: 0x396a15a8 (more...)}
 scoring_hand = table: 0x3bda76c8  {1:table: 0x3abb39e0, 2:table: 0x3aa17568, 3:table: 0x3a2aedb8, 4:table: 0x39fc4d08 (more...)}
 non_loc_disp_text = string: "Full House"
 text_repl = string: "Full House"
 disp_text_repl = string: "Full House"
 non_loc_disp_text_repl = string: "Full House"
 pures = table: 0x396a15f8  {}
 percent = number: 1.1
 percent_delta = number: 0.08
 hand_text_set = boolean: false
 modded = boolean: false
 (for index) = number: 4
 (for limit) = number: 5
 (for step) = number: 1
 i = number: 4
 reps = table: 0x3933edb0  {1:1}
 eval = table: 0x394bf118  {jokers:table: 0x3b196030}
 (for index) = number: 8
 (for limit) = number: 8
 (for step) = number: 1
 j = number: 8
(12) Lua upvalue 'gfep' at file 'main.lua:1827'
Local variables:
 e = nil
(13) Lua upvalue 'evalPlayRef' at file 'Items/Blinds.lua:1143' (from mod with id Cryptid)
Local variables:
 e = nil
(14) Lua field 'evaluate_play' at line 128 of chunk '"7923"]'
Local variables:
 e = nil
(15) Lua field 'func' at file 'functions/state_events.lua:723'
(16) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x3a0bb788  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, created_on_pause:false (more...)}
 _results = table: 0x394170b8  {blocking:true, pause_skip:false, time_done:false, completed:false}
(17) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x394a1408  {queue_last_processed:989.1666666661, queues:table: 0x394a1430, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00693354
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x394a1430  {unlock:table: 0x394a1458, other:table: 0x394a18d0, tutorial:table: 0x394a14a8 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x394a1480  {1:table: 0x3a4eea80, 2:table: 0x3a214bf8, 3:table: 0x3a0bb788, 4:table: 0x3af1e538 (more...)}
 blocked = boolean: false
 i = number: 3
 results = table: 0x394170b8  {blocking:true, pause_skip:false, time_done:false, completed:false}
(18) Lua upvalue 'gameUpdateRef' at file 'game.lua:2675'
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
 http_resp = nil
(19) Lua upvalue 'upd' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(20) Lua upvalue 'upd' at file 'main.lua:1793'
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(21) Lua upvalue 'upd' at file 'Items/Blinds.lua:1103' (from mod with id Cryptid)
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(22) Lua upvalue 'upd' at file 'Items/CodeCards.lua:3058' (from mod with id Cryptid)
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(23) Lua upvalue 'upd' at file 'Items/MiscJokers.lua:4913' (from mod with id Cryptid)
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(24) Lua upvalue 'gameUpdateRef' at file 'Cryptid.lua:1706' (from mod with id Cryptid)
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(25) Lua method 'update' at line 21 of chunk '"7923"]'
Local variables:
 self = table: 0x38ea5620  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x39f9cb00 (more...)}
 dt = number: 0.00693354
(26) Lua field 'update' at file 'main.lua:936'
Local variables:
 dt = number: 0.00693354
(27) Lua function '?' at file 'main.lua:880' (best guess)
(28) global C function 'xpcall'
(29) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 851 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Jevonnissocoolman** [comment]
This crash was fixed in newer versions of steamodded, you need to go an d update your mods

**Comment by mpcomplete** [comment]
I'm using the steammodded 0.9.8 version that is included in the recent Cryptid 0.5.0 release. Do I need a different version?

**Comment by Jevonnissocoolman** [comment]
yes, you need to go to steamodded and download the latest source code (not the release)
https://github.com/Steamopollys/Steamodded/tree/main use this link and download the zip from the green code button
