### ISSUE TITLE
Speculo interaction with boredom(?)

### ISSUE THREAD

**Issue by xehesi** [MathIsFun0/Cryptid#210]
The bug happens when I was using wormhole deck, I have speculo, scrabble tile, mhili mepper, and boredom, the copies of boredom I have when the crash happens when I have 4 boredoms including the original. The crash log: 

Oops! The game crashed:
functions/state_events.lua:901: 'for' limit must be a number

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: 1.0.0~ALPHA-0906b-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Priority: 1e+299, Version: 0.5.0, Uses Lovely]
    2: Talisman by MathIsFun_, Mathguy24, jenwalter666 [ID: Talisman, Version: 2.0.0-beta7, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua field 'callback' at file 'functions/state_events.lua:901'
Local variables:
 card = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 ret = table: 0x01b88f20  {joker_repetitions:table: 0x01b88fb8}
 (for index) = number: 1
 (for limit) = nil
 (for step) = number: 1
 (*temporary) = table: 0x01b88f20  {joker_repetitions:table: 0x01b88fb8}
 (*temporary) = number: 2
 (*temporary) = table: 0x01642ab8  {repetitions:1, message:Again!, card:table: 0x00edc2d8}
 (*temporary) = nil
 (*temporary) = string: "'for' limit must be a number"
(4) Lua upvalue 'ccj' at Steamodded file 'core/overrides.lua:2120' 
Local variables:
 self = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 context = table: 0x00bf5d28  {callback:function: 0x01b88db8, other_card:table: 0x01819000, poker_hands:table: 0x0147f088 (more...)}
 ret = table: 0x01b88f20  {joker_repetitions:table: 0x01b88fb8}
 triggered = boolean: true
 _ret = nil
(5) Lua upvalue 'cj' at file 'main.lua:1681'
Local variables:
 self = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 context = table: 0x00bf5d28  {callback:function: 0x01b88db8, other_card:table: 0x01819000, poker_hands:table: 0x0147f088 (more...)}
(6) Lua upvalue 'cj' at file 'Cryptid.lua:676' (from mod with id Cryptid)
Local variables:
 self = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 context = table: 0x00bf5d28  {callback:function: 0x01b88db8, other_card:table: 0x01819000, poker_hands:table: 0x0147f088 (more...)}
 ggpn = number: 1
 orig_ability = table: 0x01b88e70  {bonus:0, h_mult:0, extra:table: 0x01b88ed0, x_chips:0, hands_played_at_create:7 (more...)}
 in_context_scaling = boolean: false
(7) Lua method 'calculate_joker' at file 'Items/CodeCards.lua:3083' (from mod with id Cryptid)
Local variables:
 self = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 context = table: 0x00bf5d28  {callback:function: 0x01b88db8, other_card:table: 0x01819000, poker_hands:table: 0x0147f088 (more...)}
(8) Lua upvalue 'ec' at file 'functions/common_events.lua:681'
Local variables:
 card = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 context = table: 0x00bf5d28  {callback:function: 0x01b88db8, other_card:table: 0x01819000, poker_hands:table: 0x0147f088 (more...)}
 enhancement_calculated = boolean: false
 center = table: 0x01190b98  {alerted:true, loc_vars:function: 0x01190f18, object_type:Joker, _saved_d_u:true (more...)}
 ret = table: 0x01b88de0  {}
 chips = number: 0
 mult = number: 0
 x_mult = number: 0
 x_chips = number: 0
 e_chips = number: 0
 ee_chips = number: 0
 eee_chips = number: 0
 hyper_chips = table: 0x00bf5d50  {1:0, 2:0}
 e_mult = number: 0
 ee_mult = number: 0
 eee_mult = number: 0
 hyper_mult = table: 0x01b88e08  {1:0, 2:0}
 p_dollars = number: 0
(9) Lua global 'eval_card' at file 'Cryptid.lua:325' (from mod with id Cryptid)
Local variables:
 card = table: 0x00edc2d8  {click_offset:table: 0x00b64850, children:table: 0x00d34798, ambient_tilt:0.2 (more...)}
 context = table: 0x00bf5d28  {callback:function: 0x01b88db8, other_card:table: 0x01819000, poker_hands:table: 0x0147f088 (more...)}
 ggpn = number: 1
(10) Lua upvalue 'gfep' at file 'functions/state_events.lua:899'
Local variables:
 e = nil
 text = string: "High Card"
 disp_text = string: "High Card"
 poker_hands = table: 0x0147f088  {Flush House:table: 0x00db53a8, Full House:table: 0x00db5408, top:table: 0x00db55b0 (more...)}
 scoring_hand = table: 0x0147f118  {1:table: 0x01819000}
 non_loc_disp_text = string: "High Card"
 text_repl = string: "High Card"
 disp_text_repl = string: "High Card"
 non_loc_disp_text_repl = string: "High Card"
 pures = table: 0x00db5788  {}
 percent = number: 0.3
 percent_delta = number: 0.08
 hand_text_set = boolean: false
 modded = boolean: false
 (for index) = number: 1
 (for limit) = number: 1
 (for step) = number: 1
 i = number: 1
 reps = table: 0x0138e858  {1:1, 2:table: 0x0147fea8, 3:table: 0x017bcd80, 4:table: 0x00c73f38, 5:table: 0x009e5e60 (more...)}
 eval = table: 0x00859d18  {jokers:table: 0x01b88f20}
 (for index) = number: 9
 (for limit) = number: 10
 (for step) = number: 1
 j = number: 9
(11) Lua upvalue 'gfep' at file 'main.lua:1695'
Local variables:
 e = nil
(12) Lua field 'evaluate_play' at file 'Items/Blinds.lua:1143' (from mod with id Cryptid)
Local variables:
 e = nil
(13) Lua field 'func' at file 'functions/state_events.lua:723'
(14) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x00ba30c8  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x018186e0 (more...)}
 _results = table: 0x00fe4f10  {blocking:true, pause_skip:false, time_done:false, completed:false}
(15) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x00b519c8  {queue_last_processed:204.86666666672, queues:table: 0x00b52310, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00519868
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x00b52310  {unlock:table: 0x00b52d48, other:table: 0x00b552a0, tutorial:table: 0x00b54028 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x00b536f8  {1:table: 0x009f8640, 2:table: 0x010c66d0, 3:table: 0x00ba30c8, 4:table: 0x00b1f8e0 (more...)}
 blocked = boolean: false
 i = number: 3
 results = table: 0x00fe4f10  {blocking:true, pause_skip:false, time_done:false, completed:false}
(16) Lua upvalue 'gameUpdateRef' at file 'game.lua:2671'
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
 http_resp = nil
(17) Lua upvalue 'upd' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
(18) Lua upvalue 'upd' at file 'main.lua:1661'
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
(19) Lua upvalue 'upd' at file 'Items/Blinds.lua:1103' (from mod with id Cryptid)
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
(20) Lua upvalue 'upd' at file 'Items/CodeCards.lua:3058' (from mod with id Cryptid)
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
(21) Lua upvalue 'upd' at file 'Items/MiscJokers.lua:4913' (from mod with id Cryptid)
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
(22) Lua method 'update' at file 'Cryptid.lua:1706' (from mod with id Cryptid)
Local variables:
 self = table: 0x005fe320  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0138c0e8 (more...)}
 dt = number: 0.00519868
(23) Lua field 'update' at file 'main.lua:936'
Local variables:
 dt = number: 0.00519868
(24) Lua function '?' at file 'main.lua:880' (best guess)
(25) global C function 'xpcall'
(26) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 851 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by MathIsFun0** [comment]
This has already been fixed. You must update Steamodded, the version bundled with the 0.5.0 release has this issue.
