### ISSUE TITLE
Link for Steammodded Alpha 1.0 downloads .9.8

### ISSUE THREAD

**Issue by Holdeenyo** [MathIsFun0/Cryptid#38]
As the title says, when I use the link that says alpha 1.0.0, it just gives me the 0.9.8 file instead. I've been unable to locate the alpha anywehere

**Comment by MathIsFun0** [comment]
To install it, you must download the source code of Steamodded's GitHub page.
Here is a direct link: https://github.com/Steamopollys/Steamodded/archive/refs/heads/main.zip

**Comment by Holdeenyo** [comment]
that link downloads .9.8 if I'm doing this correctly

**Comment by MathIsFun0** [comment]
You probably have that installed through the injector method. You'll have to Verify Game Integrity in Steam to remove it, and install Lovely to load Steamodded 1.0
