### ISSUE TITLE
Game crash every time I select a deck 

### ISSUE THREAD

**Issue by RozzieTheJester** [MathIsFun0/Cryptid#39]
Oops! The game crashed:
C:\Users\jaces\AppData\Roaming\Balatro\Mods/C...:467: attempt to call global 'to_big' (a nil value)

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-0720c-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Version: 0.4.3a]
    2: Jank Challenges by Lyman [ID: JankChallenges]
    3: JankJonklersMod by Lyman [ID: JankJonklersMod]
    4: More Fluff by notmario [ID: MoreFluff]
    5: Talisman by MathIsFun_, Mathguy24 [ID: Talisman, Version: 2.0.0-beta1]

Stack Traceback
===============
(3) Lua global 'get_blind_amount' at line 467 of chunk '"C:\Users\jaces\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 ante = number: 1
 (*temporary) = nil
 (*temporary) = number: 0.7
 (*temporary) = number: 9.97186e-301
 (*temporary) = table: 0x017c8f98  {1:0.2156862745098, 2:0.25882352941176, 3:0.26666666666667, 4:1}
 (*temporary) = table: 0x0209ff68  {1:0.27058823529412, 2:0.31070588235294, 3:0.318, 4:1}
 (*temporary) = nil
 (*temporary) = number: 4.04231e-301
 (*temporary) = table: 0x017c8f98  {1:0.2156862745098, 2:0.25882352941176, 3:0.26666666666667, 4:1}
 (*temporary) = number: 4
 (*temporary) = number: 0
 (*temporary) = boolean: false
 (*temporary) = string: "REAL"
 (*temporary) = string: "attempt to call global 'to_big' (a nil value)"
(4) Lua upvalue 'bsb' at file 'blind.lua:114'
Local variables:
 self = table: 0x02cd88d8  {click_offset:table: 0x01f9c2b8, static_rotation:false, ambient_tilt:0.3 (more...)}
 blind = nil
 reset = nil
 silent = boolean: true
 obj = table: 0x020933a0  {}
(5) Lua function '?' at line 1115 of chunk '"C:\Users\jaces\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x02cd88d8  {click_offset:table: 0x01f9c2b8, static_rotation:false, ambient_tilt:0.3 (more...)}
 blind = nil
 y = nil
 z = boolean: true
 c = string: "Boss"
(6) Lua upvalue 'sr' at file 'game.lua:2406'
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 args = table: 0x01bd01b0  {stake:1}
 saveTable = nil
 selected_back = table: 0x01cc9af8  {order:1, _d:true, set:Back, stake:1, key:b_red, discovered:true, alerted:true (more...)}
 CAI = table: 0x0191ef70  {hand_W:12.292682926829, joker_H:2.6136585365854, joker_W:10.039024390244 (more...)}
(7) Lua method 'start_run' at line 1104 of chunk '"C:\Users\jaces\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 args = table: 0x01bd01b0  {stake:1}
(8) Lua field 'func' at file 'functions/button_callbacks.lua:2988'
(9) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x0171e488  {start_timer:true, timer:REAL, func:function: 0x01b61a00, blockable:true (more...)}
 _results = table: 0x02cba558  {blocking:true, pause_skip:false, time_done:false, completed:false}
(10) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x01d2f070  {queue_last_processed:9.2, queues:table: 0x01d2f098, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00190923
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x01d2f098  {unlock:table: 0x01d2f0c0, other:table: 0x01d2f538, tutorial:table: 0x01d2f110 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x01d2f0e8  {1:table: 0x0171e488, 2:table: 0x01cf1708, 3:table: 0x01fddc38, 4:table: 0x01d971c8 (more...)}
 blocked = boolean: false
 i = number: 1
 results = table: 0x02cba558  {blocking:true, pause_skip:false, time_done:false, completed:false}
(11) Lua upvalue 'gameUpdateRef' at file 'game.lua:2484'
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0
 http_resp = nil
(12) Lua upvalue 'upd' at file 'main.lua:479'
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00190923
(13) Lua upvalue 'upd' at line 1038 of chunk '"C:\Users\jaces\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00190923
(14) Lua upvalue 'upd' at line 1917 of chunk '"C:\Users\jaces\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00190923
(15) Lua upvalue 'game_updateref' at file 'Cryptid.lua:633' (from mod with id Cryptid)
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00190923
(16) Lua method 'update' at file 'MoreFluff.lua:139' (from mod with id MoreFluff)
Local variables:
 self = table: 0x017c2d88  {PALETTE:table: 0x019a3e08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00190923
(17) Lua field 'update' at file 'main.lua:133'
Local variables:
 dt = number: 0.00190923
(18) Lua function '?' at file 'main.lua:77' (best guess)
(19) global C function 'xpcall'
(20) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 48 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by MathIsFun0** [comment]
Talisman is not installed properly, watch the [install guide](https://www.youtube.com/watch?v=aUr0gXE77rk)
