### ISSUE TITLE
Steamodded version question

### ISSUE THREAD

**Issue by BalatroUser69** [MathIsFun0/Cryptid#4]
the mod just won't work for me even though it is in the mod directory, im assuming its because the description says to have Steamodded Alpha 1.0.0 but i only have 0.9.8 and i cant seem to find 1.0.0

**Comment by MathIsFun0** [comment]
To use Steamodded 1.0.0 (required for Cryptid), download the latest code from Steamodded's GitHub and install it with the Lovely method. Note that most Steamodded mods are currently incompatible with 1.0.0.
