### ISSUE TITLE
Cryptid somehow breaks the game - Balatro ran fine without it and I don't understand what's wrong.

### ISSUE THREAD

**Issue by rolandthedragon** [MathIsFun0/Cryptid#43]
Oops! The game crashed:
game.lua:96: Failed to collect file data for sound_manager

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-0722a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6

Stack Traceback
===============
(3) global C function 'assert'
(4) Lua global 'initSoundManager' at file 'game.lua:96'
Local variables:
 full_path = string: "C:/Users/galin/AppData/Roaming/Balatro/Mods/Cryptid/sound_manager.lua"
(5) Lua upvalue 'su' at file 'game.lua:107'
Local variables:
 self = table: 0x210aa1a0  {PALETTE:table: 0x210785d8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_HIDE_BG:false (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1f-FULL\",[\"ambient_control\"]={[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=0,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=0,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=0,},[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=0,},},[\"QUEUED_CHANGE\"]={},[\"screenshake\"]=50,[\"colourblind_option\"]=true,[\"play_button_pos\"]=2,[\"profile\"]=1,[\"selected_colours\"]={[\"Spectral\"]={[\"order\"]=1,[\"old_colours\"]={},[\"name\"]=\"Default\",[\"new_colours\"]={},},[\"Tarot\"]={[\"order\"]=1,[\"old_colours\"]={},[\"name\"]=\"Default\",[\"new_colours\"]={},},[\"Planet\"]={[\"order\"]=1,[\"old_colours\"]={},[\"name\"]=\"Default\",[\"new_colours\"]={},},[\"Suits\"]={[\"order\"]=1,[\"old_colours\"]={[4]={[4]=1,[1]=0.94117647058824,[2]=0.20392156862745,[3]=0.3921568627451,},[1]={[4]=1,[1]=0.13725490196078,[2]=0.34901960784314,[3]=0.33333333333333,},[2]={[4]=1,[1]=0.23529411764706,[2]=0.26274509803922,[3]=0.4078431372549,},[3]={[4]=1,[1]=0.94117647058824,[2]=0.41960784313725,[3]=0.24705882352941,},},[\"name\"]=\"Default\",[\"new_colours\"]={[4]={[4]=1,[1]=0.94117647058824,[2]=0.20392156862745,[3]=0.3921568627451,},[1]={[4]=1,[1]=0.13725490196078,[2]=0.34901960784314,[3]=0.33333333333333,},[2]={[4]=1,[1]=0.23529411764706,[2]=0.26274509803922,[3]=0.4078431372549,},[3]={[4]=1,[1]=0.94117647058824,[2]=0.41960784313725,[3]=0.24705882352941,},},},},[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"hold_parts\"]={[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"second_hand\"]=true,[\"shop_1\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},[\"section\"]=\"second_hand\",[\"completed_parts\"]={[\"first_hand\"]=true,[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"shop_1\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"second_hand\"]=true,},},[\"WINDOW\"]={[\"vsync\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Fullscreen\",[\"DISPLAYS\"]={[1]={[\"screen_resolutions\"]={[\"strings\"]={[2]=\"1760 X 990\",[5]=\"1366 X 768\",[11]=\"640 X 480\",[4]=\"1600 X 900\",[10]=\"800 X 600\",[9]=\"1024 X 768\",[8]=\"1128 X 634\",[3]=\"1680 X 1050\",[7]=\"1280 X 720\",[1]=\"1920 X 1080\",[6]=\"1280 X 1024\",},[\"values\"]={[2]={[\"w\"]=1760,[\"h\"]=990,},[5]={[\"w\"]=1366,[\"h\"]=768,},[11]={[\"w\"]=640,[\"h\"]=480,},[4]={[\"w\"]=1600,[\"h\"]=900,},[10]={[\"w\"]=800,[\"h\"]=600,},[9]={[\"w\"]=1024,[\"h\"]=768,},[8]={[\"w\"]=1128,[\"h\"]=634,},[3]={[\"w\"]=1680,[\"h\"]=1050,},[7]={[\"w\"]=1280,[\"h\"]=720,},[1]={[\"w\"]=1920,[\"h\"]=1080,},[6]={[\"w\"]=1280,[\"h\"]=1024,},},},[\"screen_res\"]={[\"w\"]=1920,[\"h\"]=1080,},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=1080,[\"width\"]=1920,},},},[\"selected_display\"]=1,},[\"language\"]=\"en-us\",[\"GAMESPEED\"]=4,[\"SOUND\"]={[\"volume\"]=50,[\"music_volume\"]=100,[\"game_sounds_volume\"]=100,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"card_discarder\"]=true,[\"_10k\"]=true,[\"retrograde\"]=true,[\"royale\"]=true,[\"_100000k\"]=true,[\"cartomancy\"]=true,[\"low_stakes\"]=true,[\"ante_upper\"]=true,[\"astronomy\"]=true,[\"shattered\"]=true,[\"legendary\"]=true,[\"heads_up\"]=true,[\"roi\"]=true,[\"_1000k\"]=true,[\"clairvoyance\"]=true,[\"ante_up\"]=true,[\"card_player\"]=true,},[\"tutorial_complete\"]=true,[\"current_setup\"]=\"New Run\",[\"COMP\"]={[\"prev_name\"]=\"\",[\"name\"]=\"\",[\"score\"]=17376554675.2,},[\"paused\"]=false,[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=15.021960978978,},[\"GRAPHICS\"]={[\"texture_scaling\"]=2,[\"crt\"]=70,[\"shadows\"]=\"On\",[\"bloom\"]=1,},}"
 settings_ver = nil
 new_colour_proto = table: 0x210b20a8  {Spades:table: 0x210b2310, Hearts:table: 0x210b21c0, Diamonds:table: 0x210b2278 (more...)}
 sound_files = table: 0x210ab038  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
(6) Lua method 'start_up' at file 'main.lua:1642'
Local variables:
 self = table: 0x210aa1a0  {PALETTE:table: 0x210785d8, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_HIDE_BG:false (more...)}
(7) Lua field 'load' at file 'main.lua:879'
(8) Lua function '?' at file 'main.lua:826' (best guess)
(9) global C function 'xpcall'
(10) Love2D function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(11) global C function 'xpcall'
(12) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Jevonnissocoolman** [comment]
make sure the folder is named EXACTLY **Cryptid** -game will have issues otherwise

**Comment by rolandthedragon** [comment]
I did not know I had to do that - the folder was named Cryptid-main because that's how it came by default. Now it's once again perfectly fine, thank you so SO much!
