### ISSUE TITLE
Crash when resolving Tag "upgrade [poker hand]"

### ISSUE THREAD

**Issue by mpcomplete** [MathIsFun0/Cryptid#99]
I generated a bunch of skip tags with the Pickle (duplicated via Blueprinted Chads). I noticed several of them were of the "Upgrade poker hand" type, except the poker hand in question was listed as "[poker hand]". When I choose "next run", the game crashes.

Here's the call stack:

Oops! The game crashed:
tag.lua:203: attempt to index a nil value

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-0720a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Better Mouse And Gamepad by Kooluve [ID: BetterMouseAndGamepad]
    2: Cryptid by MathIsFun_, Balatro Discord [ID: Cryptid, Version: 0.4.3a]
    3: Talisman by MathIsFun_, Mathguy24 [ID: Talisman, Version: 2.0.0-beta1]

Stack Traceback
===============
(3) Lua upvalue 'tapr' at file 'tag.lua:203'
Local variables:
 self = table: 0x17575a90  {tally:82, triggered:false, tag_sprite:table: 0x17594fc0, pos:table: 0x165cf2f8 (more...)}
 _context = table: 0x16129f38  {type:immediate}
 obj = nil
 res = nil
 lock = number: 9
 (*temporary) = Lua function '?' (defined at line 466 of chunk "C:\Users\mpcom\AppData\Roaming\Balatro\Mods/C..."])
 (*temporary) = table: 0x16129f98  {sound:button, volume:0.7, pitch:0.8, delay:0.3}
 (*temporary) = table: 0x1612a028  {handname:[poker hand]}
 (*temporary) = nil
 (*temporary) = string: "[poker hand]"
 (*temporary) = table: 0x16383808  {velocity:table: 0x16805a08, click_offset:table: 0x16805ac8, UIT:4, children:table: 0x168f1708 (more...)}
 (*temporary) = nil
 (*temporary) = number: 1
 (*temporary) = number: 13.16
 (*temporary) = number: 31.16
 (*temporary) = string: "attempt to index a nil value"
(4) Lua method 'apply_to_run' at line 631 of chunk '"C:\Users\mpcom\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x17575a90  {tally:82, triggered:false, tag_sprite:table: 0x17594fc0, pos:table: 0x165cf2f8 (more...)}
 x = table: 0x16129f38  {type:immediate}
(5) Lua field 'func' at file 'game.lua:3452'
Local variables:
 (for index) = number: 10
 (for limit) = number: 11
 (for step) = number: 1
 i = number: 10
(6) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x169eb740  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x174b0568 (more...)}
 _results = table: 0x16820700  {blocking:true, pause_skip:false, time_done:false, completed:false}
(7) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x1646f8b0  {queue_last_processed:21.083333333333, queues:table: 0x1646f9c8, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00708684
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x1646f9c8  {unlock:table: 0x1646fb08, other:table: 0x164055c8, tutorial:table: 0x164cd6a8 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x1646fc10  {1:table: 0x1705b370, 2:table: 0x175ae938, 3:table: 0x175ae960, 4:table: 0x175ae988 (more...)}
 blocked = boolean: false
 i = number: 18
 results = table: 0x16820700  {blocking:true, pause_skip:false, time_done:false, completed:false}
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2654'
Local variables:
 self = table: 0x15f897b8  {PALETTE:table: 0x15edbd08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00708684
 http_resp = nil
(9) Lua upvalue 'upd' at file 'main.lua:498'
Local variables:
 self = table: 0x15f897b8  {PALETTE:table: 0x15edbd08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00708684
(10) Lua upvalue 'upd' at file 'main.lua:8249'
Local variables:
 self = table: 0x15f897b8  {PALETTE:table: 0x15edbd08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00708684
(11) Lua upvalue 'upd' at line 1038 of chunk '"C:\Users\mpcom\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x15f897b8  {PALETTE:table: 0x15edbd08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00708684
(12) Lua upvalue 'upd' at line 1917 of chunk '"C:\Users\mpcom\AppData\Roaming\Balatro\Mods/C..."]'
Local variables:
 self = table: 0x15f897b8  {PALETTE:table: 0x15edbd08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00708684
(13) Lua method 'update' at file 'Cryptid.lua:633' (from mod with id Cryptid)
Local variables:
 self = table: 0x15f897b8  {PALETTE:table: 0x15edbd08, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.00708684
(14) Lua field 'update' at file 'main.lua:133'
Local variables:
 dt = number: 0.00708684
(15) Lua function '?' at file 'main.lua:77' (best guess)
(16) global C function 'xpcall'
(17) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 48 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by Jevonnissocoolman** [comment]
I think this should be fixed by now, gonna go and close this
